<?php

namespace AppBundle\Repository;

/**
 * DomainEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
