<?php

namespace AppBundle\Repository;

/**
 * UserRegistrationEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRegistrationEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
